spring.application.name=turbrasil

#CREDENTIALS DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#CONFIG DATABASE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT KEYS
jwt.private-key=file:${JWT_PRIVATE_KEY}
jwt.public-key=file:${JWT_PUBLIC_KEY}

